endpoint = "https://s3.eu-north-1.amazonaws.com"
token = "+aSADHsg9EmTdgMGoQo1YJWr/2f7sjHzi2kgu5Lx"
remote_path = "s3://dev-sync-bucket-odingrif-462292558512-eu-north-1-an/test-folder"
local_path = "./local_data"
log_path = "./sync.log"
max_file_age_ms = 10000
delete_old_files = true
sync_mode = "pull"
polling_interval_ms = 10000
timeout_ms = 1
match_regex = ".*\\.txt$"
refetch_deleted_file = false
version = 1